"""Shared state definitions for the LangGraph workflow.

LangGraph passes a single typed state object between nodes. This module defines
both that state shape and the structured response model used when asking the
LLM to produce search queries.
"""

from __future__ import annotations

import operator
from typing import Annotated, List, TypedDict

from pydantic import BaseModel, Field


class AgentState(TypedDict):
    """State carried through the essay-writing graph.

    Fields:
        task: Original essay topic/request entered by the user.
        lnode: Name of the last graph node that executed successfully.
        plan: High-level outline generated before drafting begins.
        draft: Most recent essay draft.
        critique: Most recent feedback produced by the reflection step.
        content: Accumulated research snippets returned from Tavily.
        queries: Most recent search queries generated by the model.
        revision_number: Number of drafts produced so far.
        max_revisions: Configured upper bound for draft generation cycles.
        count: Simple additive counter used to label graph progress in the UI.
    """

    task: str
    lnode: str
    plan: str
    draft: str
    critique: str
    content: List[str]
    queries: List[str]
    revision_number: int
    max_revisions: int
    count: Annotated[int, operator.add]


class Queries(BaseModel):
    """Structured LLM output for search-query generation."""

    queries: list[str] = Field(
        default_factory=list,
        description="List of search-engine queries to run for research.",
    )
